message:
  no-item: "&f–£ –≤–∞—Å –Ω–µ—Ç –ø—Ä–µ–¥–º–µ—Ç–∞ &a%item_name%"
  yast-buyer: "&f–í—ã —É—Å–ø–µ—à–Ω–æ –ø—Ä–æ–¥–∞–ª–∏ &a%item_name% &f–∑–∞ &#4A90E2%prince%"
  autosell: "&f–í—ã –ø—Ä–æ–¥–∞–ª–∏ —Å–∫—É–ø—â–∏–∫—É &#FFFFFF%item_sell% &f —à—Ç—É–∫ –±–∞–ª–∞–Ω—Å &a%balance%"
  autosell-on: "&f–ê–≤—Ç–æ-—Å–∫—É–ø—â–∏–∫ %autobuyer_status%"
  autosell-off: "&f–ê–≤—Ç–æ-—Å–∫—É–ø—â–∏–∫ %autobuyer_status%"
  no-permission: "&4–£ –≤–∞—Å –Ω–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –ø—Ä–∞–≤"
  level-up: "&#4A90E2üéâ –í—ã –¥–æ—Å—Ç–∏–≥–ª–∏ —É—Ä–æ–≤–Ω—è &#FFFFFF%new_level%"
  level-info:
    - "&f–í–∞—à–∞ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ —É—Ä–æ–≤–Ω–µ–π"
    - ""
    - "&f–û–±—â–∞—è —Å—É–º–º–∞ –ø—Ä–æ–¥–∞–∂ %buyer_total_earned%"
    - "&f–¢–µ–∫—É—â–∏–π —É—Ä–æ–≤–µ–Ω—å %buyer_current_level%"
    - "&f–î–æ —Å–ª–µ–¥—É—é—â–µ–≥–æ —É—Ä–æ–≤–Ω—è %buyer_required_amount%"
placeholder:
  enable-autobuyer: "&#00BFFF‚úì –í–∫–ª—é—á–µ–Ω"
  disable-autobuyer: "&#FF6B6B‚úó –í—ã–∫–ª—é—á–µ–Ω"

sound_open_menu: BLOCK_CHEST_OPEN
no-item-sound: ENTITY_VILLAGER_NO
autobuyer-sound: BLOCK_NOTE_BLOCK_XYLOPHONE

autobuyer-bossbar:
  autobuyer-bossbar-text: "&f–£ –≤–∞—Å &a–≤–∫–ª—é—á—ë–Ω &c–∞–≤—Ç–æ-—Å–∫—É–ø—â–∏–∫"
  autobuyer-bossbar-color: RED
  autobuyer-time: 40

levels:
  1:
    multiplier: 0.0
    required-money: 0.0
  2:
    multiplier: 0.1
    required-money: 1000.0
  3:
    multiplier: 0.2
    required-money: 5000.0
  4:
    multiplier: 0.3
    required-money: 10000.0
  5:
    multiplier: 0.5
    required-money: 50000.0

register-menu:
  - "menu/menu.yml"
  - "menu/mine.yml"
  - "menu/farm.yml"
  - "menu/ast.yml"